version: '3'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 11080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/jboss/keycloak/standalone/data
